name: Contracts

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "contracts/**"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_PULL_TOKEN }}
          fetch-depth: 2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Ensure files are formatted correctly
        working-directory: ./contracts
        run: forge fmt src/ test/ script/ --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_PULL_TOKEN }}
          fetch-depth: 2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build the contracts and print their size
        working-directory: ./contracts
        run: forge build --sizes

      - name: Add build summary
        run: echo "## Build result\n✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    name: Test
    needs: [format, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_PULL_TOKEN }}
          fetch-depth: 2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Generate a fuzz seed that changes weekly
        run: echo "FOUNDRY_FUZZ_SEED=$(( $(date +%s) - $(date +%s) % 604800 ))" >> $GITHUB_ENV

      - name: Run the tests
        working-directory: ./contracts
        run: forge test

      - name: Add test summary
        run: echo "## Tests result\n✅ Passed" >> $GITHUB_STEP_SUMMARY
